name: emoly_flutter
description: Emoly Flutter App for Emotion Recognition Experiment
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  just_audio: ^0.9.36
  cupertino_icons: ^1.0.2
  path_provider: ^2.1.2
  video_player: ^2.7.0
  csv: ^6.0.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.4.0
  mqtt_client: ^10.0.0
  async: ^2.12.0
  material_color_utilities: ^0.11.1
  http: ^1.2.1 # For making HTTP requests

dev_dependencies:
  flutter_test:
    sdk: flutter

  fake_async: ^1.3.2
  leak_tracker: ^10.0.8
  vm_service: ^15.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/videos/
    - assets/sam/
    - assets/music/
    - assets/logo/
    ##- assets/lang/
   
